apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubevis
spec:
  selector:
    matchLabels:
      component: kubevis
  replicas: 1
  template:
    metadata:
      labels:
        component: kubevis
    spec:
      containers:
        - name: kubevis
          image: kubevis-dev:${DATE_TAG}
          imagePullPolicy: Never
          ports:
            - containerPort: 3000